import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Item={nome:string;quantidade:number;total:number;adicionais:string[];removidos:string|null;observacoes:string|null};
type Order={id:string;codigo:string;cliente_nome:string;tipo:string;status:string;total:number;criado_em:string;itens:Item[]};
const labels:Record<string,string>={recebido:"Pedido recebido",confirmado:"Confirmado",em_preparo:"Em preparo",pronto:"Pronto",saiu_para_entrega:"Saiu para entrega",concluido:"Concluído",cancelado:"Cancelado"};
const steps=["recebido","confirmado","em_preparo","pronto","saiu_para_entrega","concluido"];
export const Route=createFileRoute("/pedido/$token")({component:TrackOrder});
function TrackOrder(){
 const {token}=Route.useParams(); const [order,setOrder]=useState<Order|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;const load=async()=>{if(!supabase)return;const {data}=await supabase.rpc("consultar_pedido_publico",{p_token:token});if(alive)setOrder((data??null) as Order|null);setLoading(false)};load();const timer=window.setInterval(load,5000);return()=>{alive=false;window.clearInterval(timer)}},[token]);
 if(loading)return <main className="grid min-h-screen place-items-center">Carregando pedido...</main>;
 if(!order)return <main className="grid min-h-screen place-items-center px-5"><div className="text-center"><h1 className="font-display text-4xl">Pedido não encontrado</h1><p className="mt-3 text-muted-foreground">Confira o link do pedido.</p><Link to="/" className="mt-6 inline-flex rounded-xl bg-primary px-5 py-3 text-primary-foreground">Voltar ao cardápio</Link></div></main>;
 const active=Math.max(0,steps.indexOf(order.status));
 return <main className="min-h-screen bg-background px-4 py-10 sm:px-8"><div className="mx-auto max-w-2xl"><Link to="/" className="text-sm text-muted-foreground hover:text-foreground">← Cardápio</Link><div className="mt-8 rounded-3xl border bg-card p-6 shadow-sm sm:p-8"><p className="text-xs uppercase tracking-[.25em] text-primary">Acompanhe seu pedido</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><h1 className="font-display text-4xl">{order.codigo}</h1><span className="rounded-full bg-primary/10 px-3 py-1 text-sm text-primary">{labels[order.status]??order.status}</span></div>{order.status==="cancelado"?<div className="mt-8 rounded-xl border border-red-500/20 bg-red-500/5 p-4 text-red-300">Este pedido foi cancelado.</div>:<div className="mt-8 space-y-5">{steps.map((step,i)=><div key={step} className="flex items-center gap-3"><span className={"grid h-8 w-8 shrink-0 place-items-center rounded-full border text-xs "+(i<=active?"border-primary bg-primary text-primary-foreground":"border-border text-muted-foreground")}>{i<active?"✓":i+1}</span><span className={i<=active?"font-medium":"text-muted-foreground"}>{labels[step]}</span></div>)}</div>}<div className="mt-8 border-t pt-6"><h2 className="font-semibold">Itens</h2><div className="mt-3 space-y-3">{order.itens?.map((item,i)=><div key={i} className="flex justify-between gap-4 text-sm"><div><b>{item.quantidade}x {item.nome}</b>{item.adicionais?.length>0&&<p className="text-xs text-muted-foreground">+ {item.adicionais.join(", ")}</p>}{item.removidos&&<p className="text-xs text-muted-foreground">Sem: {item.removidos}</p>}</div><span>{Number(item.total).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</span></div>)}</div><div className="mt-5 flex justify-between border-t pt-4 text-lg font-semibold"><span>Total</span><span>{Number(order.total).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</span></div></div><p className="mt-6 text-center text-xs text-muted-foreground">Atualizamos o status automaticamente.</p></div></div></main>;
}